security:
  ignore-vulnerabilities:
    61893:
      reason: Required for sphinx until 3.8 support is removed.
      expires: "2024-06-01"
    61601:
      reason: Required for sphinx until 3.8 support is removed.
      expires: "2024-06-01"
    61949:
      reason: Required for sphinx until 3.8 support is removed.
      expires: "2024-06-01"
    64227:
      reason: Required for sphinx until 3.8 support is removed.
      expires: "2024-06-01"
